// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knimvpizylhpvklhzldw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuaW12cGl6eWxocHZrbGh6bGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Nzg0NTYsImV4cCI6MjA2NzM1NDQ1Nn0.dNz3x8E3Hiynj7AnakWKSQ1hz7K6A4McEhqU0VKE-z4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});